services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: microbiome-api-backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - microbiome-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: microbiome-api-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - microbiome-network
    restart: unless-stopped

networks:
  microbiome-network:
    driver: bridge
